-- 切換資料庫
USE TSQL_PRACTICE
GO

--  建立I1產品資料表 (SID, 產品名稱, 售價)
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[I1]') 
	AND type in (N'U')
) DROP TABLE [dbo].[I1]
CREATE TABLE [I1] 
(
	I101 NUMERIC(25,0) IDENTITY (1, 1) NOT FOR REPLICATION  NOT NULL,
	I102 NVARCHAR(50) NOT NULL,
	I103 NUMERIC(25,4) NOT NULL 
)
GO

--  建立I2產品資料異動記錄表 (SID, 異動狀態, I101, I102, I103)
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[I2]') 
	AND type in (N'U')
) DROP TABLE [dbo].[I2]
CREATE TABLE [I2]
(
	I201 NUMERIC(25,0) IDENTITY (5,5) NOT FOR REPLICATION  NOT NULL,
	I202 NVARCHAR(50) NOT NULL,
	I203 NUMERIC(25,0) NOT NULL,
	I204 NVARCHAR(50) NOT NULL,
	I205 NUMERIC(25,4) NOT NULL 
)
GO


