-- 建立公司資料表
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[COMPANY]') 
	AND type in (N'U')
) DROP TABLE [dbo].[COMPANY]
CREATE TABLE [COMPANY]
(
	ID NVARCHAR(2),
	NAME NVARCHAR(40)
)

-- 建立部門資料表
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[DEPARTMENT]') 
	AND type in (N'U')
) DROP TABLE [dbo].[DEPARTMENT]
CREATE TABLE [DEPARTMENT]
(
	ID NVARCHAR(6),
	NAME NVARCHAR(40),
	MANAGERID NVARCHAR(10)
)

-- 建立員工資料表
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEE]') 
	AND type in (N'U')
) DROP TABLE [dbo].[EMPLOYEE]
CREATE TABLE [EMPLOYEE]
(
	ID NVARCHAR(10),
	NAME NVARCHAR(20),
	DEPTID NVARCHAR(6)
)

-- 建立客戶資料表
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[CS]') 
	AND type in (N'U')
) DROP TABLE [dbo].[CS]
CREATE TABLE [CS]
(
	ID NVARCHAR(10),
	NAME NVARCHAR(40),
	DTYPE NVARCHAR(1),
	SALES NVARCHAR(10)
)

-- 建立產品類別資料表
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[PRODUCTCATEGORY]') 
	AND type in (N'U')
) DROP TABLE [dbo].[PRODUCTCATEGORY]
CREATE TABLE [PRODUCTCATEGORY]
(
	ID NVARCHAR(10),
	NAME NVARCHAR(40)
)

-- 建立產品資料表
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[PRODUCT]') 
	AND type in (N'U')
) DROP TABLE [dbo].[PRODUCT]
CREATE TABLE [PRODUCT]
(
	ID NVARCHAR(10),
	NAME NVARCHAR(40),
	CATEID NVARCHAR(10),
	SUPPLIERID NVARCHAR(10),
	UPRICE NUMERIC(25,4),
	QTY NUMERIC(25,4),
	UNIT NVARCHAR(20)
)

-- 建立訂單資料表
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS]') 
	AND type in (N'U')
) DROP TABLE [dbo].[ORDERS]
CREATE TABLE [ORDERS]
(
	COMPID NVARCHAR(2),
	ORDERNO NVARCHAR(10),
	SNO NUMERIC(25,4),
	ORDERDATE NVARCHAR(8),
	CUSTID NVARCHAR(10),
	PRODID NVARCHAR(10),
	QTY NUMERIC(25,4),
	UPRICE NUMERIC(25,4),
	AMOUNT NUMERIC(25,4)
)

-- 建立訂單資料表記錄檔
IF  EXISTS 
(
	SELECT * FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS_LOG]') 
	AND type in (N'U')
) DROP TABLE [dbo].[ORDERS_LOG]
CREATE TABLE [ORDERS_LOG]
(
	NO NUMERIC(25,0) IDENTITY (1,1),
	TRANSDATE NVARCHAR(8),
	TRANSTIME NVARCHAR(9),
	TRANSWS NVARCHAR(100),
	TRANSUSER NVARCHAR(100),
	TRANSTYPE NVARCHAR(1),
	COMPID NVARCHAR(2),
	ORDERNO NVARCHAR(10),
	SNO NUMERIC(25,4),
	ORDERDATE NVARCHAR(8),
	CUSTID NVARCHAR(10),
	PRODID NVARCHAR(10),
	QTY NUMERIC(25,4),
	UPRICE NUMERIC(25,4),
	AMOUNT NUMERIC(25,4)
)
