-- 建立 usp_InsertOrders 預存程序, 新增一筆訂單資料
IF OBJECT_ID(N'dbo.usp_InsertOrders', N'P') IS NOT NULL
   DROP PROCEDURE dbo.usp_InsertOrders
GO
CREATE PROCEDURE dbo.usp_InsertOrders
	@COMPID NVARCHAR(2)='',
	@ORDERNO NVARCHAR(10)='',
	@SNO NUMERIC(25,4)=0,
	@ORDERDATE NVARCHAR(8)='',
	@CUSTID NVARCHAR(10)='',
	@PRODID NVARCHAR(10)='',
	@QTY NUMERIC(25,4)=0,
	@UPRICE NUMERIC(25,4)=0,
	@AMOUNT NUMERIC(25,4)=0
AS
INSERT INTO ORDERS VALUES 
(
	@COMPID,
	@ORDERNO,
	@SNO,
	@ORDERDATE,
	@CUSTID,
	@PRODID,
	@QTY,
	@UPRICE,
	@AMOUNT
)
GO

-- 建立 usp_UpdateOrders 預存程序, 修改一筆訂單資料
IF OBJECT_ID(N'dbo.usp_UpdateOrders', N'P') IS NOT NULL
   DROP PROCEDURE dbo.usp_UpdateOrders
GO
CREATE PROCEDURE dbo.usp_UpdateOrders
	@ORDERDATE NVARCHAR(8)='',
	@CUSTID NVARCHAR(10)='',
	@PRODID NVARCHAR(10)='',
	@QTY NUMERIC(25,4)=0,
	@UPRICE NUMERIC(25,4)=0,
	@AMOUNT NUMERIC(25,4)=0,
	@COMPIDo NVARCHAR(2)='',
	@ORDERNOo NVARCHAR(10)='',
	@SNOo NUMERIC(25,4)=0
AS
UPDATE ORDERS SET 
ORDERDATE=@ORDERDATE,
CUSTID=@CUSTID,
PRODID=@PRODID,
QTY=@QTY,
UPRICE=@UPRICE,
AMOUNT=@AMOUNT
WHERE COMPID=@COMPIDo
AND ORDERNO=@ORDERNOo
AND SNO=@SNOo
GO

-- 建立 usp_DeleteOrders 預存程序, 刪除一張訂單資料
IF OBJECT_ID(N'dbo.usp_DeleteOrders', N'P') IS NOT NULL
   DROP PROCEDURE dbo.usp_DeleteOrders
GO
CREATE PROCEDURE dbo.usp_DeleteOrders
	@COMPIDo NVARCHAR(2)='',
	@ORDERNOo NVARCHAR(10)=''
AS
DELETE FROM ORDERS
WHERE COMPID=@COMPIDo
AND ORDERNO=@ORDERNOo
GO
