-- 建立 ORDERS 資料異動的Trigger
IF OBJECT_ID(N'dbo.trg_LogOrders', N'T') IS NOT NULL
   DROP TRIGGER dbo.trg_LogOrders
GO
CREATE TRIGGER dbo.trg_LogOrders
ON  dbo.ORDERS
AFTER INSERT,UPDATE,DELETE
AS
BEGIN
SET NOCOUNT ON

DECLARE @ICount INT
DECLARE @DCount INT
DECLARE @TRANSDATE VARCHAR(8)
DECLARE @TRANSTIME VARCHAR(9)
DECLARE @TRANSWS VARCHAR(100)
DECLARE @TRANSUSER VARCHAR(100)

SET @TRANSDATE=CONVERT(NVARCHAR(8),GETDATE(),112)
SET @TRANSTIME=REPLACE(CONVERT(NVARCHAR(12),GETDATE(),114),':','')
SET @TRANSWS=HOST_NAME()
SET @TRANSUSER=SUSER_NAME()

SELECT @ICount=COUNT(*) FROM INSERTED
SELECT @DCount=COUNT(*) FROM DELETED

IF @ICount>0 AND @DCount>0 
	INSERT INTO ORDERS_LOG
	SELECT @TRANSDATE,@TRANSTIME,@TRANSWS,@TRANSUSER,'U',
	DELETED.* FROM DELETED
ELSE IF @ICount>0
	INSERT INTO ORDERS_LOG
	SELECT @TRANSDATE,@TRANSTIME,@TRANSWS,@TRANSUSER,'A',
	INSERTED.* FROM INSERTED
ELSE IF @DCount>0
	INSERT INTO ORDERS_LOG
	SELECT @TRANSDATE,@TRANSTIME,@TRANSWS,@TRANSUSER,'D',
	DELETED.* FROM DELETED
END
GO
