-- 取得 2014年4月 到本年度 2015年3月 業務的產品訂貨總量及總金額，並依總金額排名
SELECT 
C.SALES,E.NAME SALESNAME,
O.PRODID,
ISNULL(P.NAME,'MISSING')  PRODNAME,
SUM(O.QTY) TOTALQTY,
SUM(AMOUNT) TOTALAMOUNT,
DENSE_RANK() OVER (PARTITION BY C.SALES ORDER BY SUM(AMOUNT) DESC) [RANK]
FROM ORDERS O
LEFT JOIN PRODUCT P
ON O.PRODID=P.ID
LEFT JOIN CS C
ON C.DTYPE='1'
AND O.CUSTID=C.ID
LEFT JOIN EMPLOYEE E
ON C.SALES=E.ID
WHERE O.COMPID='G'
AND ORDERDATE BETWEEN '20140401' AND '20150331'
GROUP BY 
C.SALES,E.NAME,
O.PRODID,
ISNULL(P.NAME,'MISSING')
ORDER BY 
C.SALES
