-- 切換資料庫
USE TSQL_PRACTICE
GO

-- 練習 : 衍生資料表
-- 出現在FROM子句中的衍生資料表 : 取得訂單資料中, 每個產品最近一筆訂單資料
SELECT * FROM
(SELECT DISTINCT PRODUCTID FROM ORDERS) P
INNER JOIN ORDERS 
ON P.PRODUCTID=ORDERS.PRODUCTID
AND ORDERS.ORDERDATE=(SELECT MAX(ORDERDATE)FROM ORDERS 
WHERE ORDERS.PRODUCTID=P.PRODUCTID)
ORDER BY P.PRODUCTID

--SELECT DISTINCT PRODUCTID,MAX(ORDERDATE) FROM ORDERS
--GROUP BY PRODUCTID
-- 使用 INNER(OR LEFT) JOIN + UNION 亦可達到以上需求
SELECT O.* FROM PRODUCT P
INNER JOIN ORDERS O
ON O.PRODUCTID=P.PRODUCTID
WHERE O.ORDERDATE=
(SELECT MAX(ORDERDATE)FROM ORDERS 
WHERE ORDERS.PRODUCTID=O.PRODUCTID)
UNION
SELECT O.* FROM ORDERS O
LEFT JOIN PRODUCT P
ON O.PRODUCTID=P.PRODUCTID
WHERE O.ORDERDATE=
(SELECT MAX(ORDERDATE)FROM ORDERS 
WHERE ORDERS.PRODUCTID=O.PRODUCTID)
ORDER BY PRODUCTID

-- 使用 FULL JOIN 亦可達到以上需求
SELECT O.* FROM PRODUCT P
FULL JOIN ORDERS O
ON O.PRODUCTID=P.PRODUCTID
WHERE O.ORDERDATE=
(SELECT MAX(ORDERDATE)FROM ORDERS 
WHERE ORDERS.PRODUCTID=O.PRODUCTID)

-- 出現在連結的衍生資料表 : 取得在 2010 年有訂單資料的所有產品
SELECT DISTINCT P.* FROM PRODUCT P
INNER JOIN 
(SELECT * FROM ORDERS
WHERE ORDERDATE BETWEEN '20100101' AND '20101231') O
ON P.PRODUCTID=O.PRODUCTID

-- 使用INNER JOIN亦可達到以上需求
SELECT DISTINCT P.* FROM PRODUCT P
INNER JOIN ORDERS O
ON P.PRODUCTID=O.PRODUCTID
WHERE ORDERDATE BETWEEN '20100101' AND '20101231'


-- 以 ORDER TABLE 為主資料表, 可帶出 2010 年未建產品主檔的資料
SELECT DISTINCT O.PRODUCTID,P.PRODUCTNAME,
P.CATEGORYID,P.PRICE,P.QTY,P.UNIT,P.DISCOUNT FROM PRODUCT P
RIGHT JOIN 
(SELECT * FROM ORDERS
WHERE ORDERDATE BETWEEN '20100101' AND '20101231') O
ON P.PRODUCTID=O.PRODUCTID
;
SELECT O.PRODUCTID,P.PRODUCTNAME,
P.CATEGORYID,P.PRICE,P.QTY,P.UNIT,P.DISCOUNT FROM
(SELECT DISTINCT PRODUCTID FROM ORDERS
WHERE ORDERDATE BETWEEN '20100101' AND '20101231') O
LEFT JOIN PRODUCT P
ON O.PRODUCTID=P.PRODUCTID
