-- 切換資料庫
USE TSQL_PRACTICE
GO

--------------------------------------------------------------------------------
-- 練習 : 使用JOIN
-- 出現在SELECT子句中的子查詢與JOIN寫法比較效能 : 找出每個產品的訂貨總次數
--------------------------------------------------------------------------------
-- @Notes: Nasted Select is somehow similar with join but performance are differnt
SELECT PRODUCTID,PRODUCTNAME,
(SELECT COUNT(*) FROM ORDERS WHERE ORDERS.PRODUCTID=PRODUCT.PRODUCTID) 訂貨總次數
FROM PRODUCT
ORDER BY 訂貨總次數 DESC
GO

SELECT P.PRODUCTID,PRODUCTNAME,COUNT(O.PRODUCTID) 訂貨總次數
FROM PRODUCT P
LEFT JOIN ORDERS O
ON P.PRODUCTID=O.PRODUCTID
GROUP BY P.PRODUCTID,PRODUCTNAME
ORDER BY 訂貨總次數 DESC
GO

--------------------------------------------------------------------------------
-- 出現在WHERE子句中的子查詢與 JOIN 寫法比較效能 : 找出產品折扣數大於 8 折的所有訂單
SELECT * FROM ORDERS
WHERE PRODUCTID IN 
(SELECT PRODUCTID FROM PRODUCT WHERE DISCOUNT>8)
GO
SELECT O.* FROM ORDERS O
LEFT JOIN PRODUCT P
ON O.PRODUCTID=P.PRODUCTID
WHERE  DISCOUNT>8

-- 出現在FROM子句中的衍生資料表與 TEMP TABLE, 資料表變數 寫法比較效能 : 取得訂單資料中, 每個產品最近一筆訂單資料
SELECT * FROM
(SELECT DISTINCT PRODUCTID FROM ORDERS) P
INNER JOIN ORDERS 
ON P.PRODUCTID=ORDERS.PRODUCTID
AND ORDERS.ORDERDATE=(SELECT MAX(ORDERDATE)FROM ORDERS 
WHERE ORDERS.PRODUCTID=P.PRODUCTID)
GO
-- 使用 SELECT INTO 產生 TEMP TABLE
SELECT DISTINCT PRODUCTID INTO #TEMP FROM ORDERS
;
SELECT * FROM #TEMP P
INNER JOIN ORDERS 
ON P.PRODUCTID=ORDERS.PRODUCTID
AND ORDERS.ORDERDATE=(SELECT MAX(ORDERDATE)FROM ORDERS 
WHERE ORDERS.PRODUCTID=P.PRODUCTID)
;
DROP TABLE #TEMP
GO
-- 使用 CREATE TABLE 產生 TEMP TABLE
CREATE TABLE #TEMP
(
	PRODUCTID VARCHAR(10)
)
;
INSERT INTO #TEMP SELECT DISTINCT PRODUCTID FROM ORDERS
;
SELECT * FROM #TEMP P
INNER JOIN ORDERS 
ON P.PRODUCTID=ORDERS.PRODUCTID
AND ORDERS.ORDERDATE=(SELECT MAX(ORDERDATE)FROM ORDERS 
WHERE ORDERS.PRODUCTID=P.PRODUCTID)
;
DROP TABLE #TEMP
GO
-- 使用 資料表變數
DECLARE @TEMP TABLE
(
	PRODUCTID VARCHAR(10)
)
;
INSERT INTO @TEMP SELECT DISTINCT PRODUCTID FROM ORDERS
;
SELECT * FROM @TEMP P
INNER JOIN ORDERS 
ON P.PRODUCTID=ORDERS.PRODUCTID
AND ORDERS.ORDERDATE=(SELECT MAX(ORDERDATE)FROM ORDERS 
WHERE ORDERS.PRODUCTID=P.PRODUCTID)
GO
