-- 切換資料庫
USE TSQL_PRACTICE
GO

-- 建立採購資料的檢視表
-- 採購資料表結合廠商, 客戶, 產品資料表, 輸出下列欄位資料 :
-- 採購日期, 廠商代號, 廠商名稱, 客戶代號, 客戶名稱, 產品代號, 產品名稱, 採購數量, 產品售價, 採購金額
IF object_id(N'dbo.uvw_Purchases', 'V') IS NOT NULL
	DROP VIEW dbo.uvw_Purchases
GO
CREATE VIEW dbo.uvw_Purchases AS
SELECT PC.PURCHASEDATE,PC.SUPPLIERID,S.SUPPLIERNAME,
PC.CUSTOMERID,C.CUSTOMERNAME,PC.PRODUCTID,P.PRODUCTNAME,
PC.QTY PurchaseQty,P.PRICE,PC.QTY*P.PRICE AMOUNT
FROM PURCHASES PC
LEFT JOIN PRODUCT P
ON PC.PRODUCTID=P.PRODUCTID
LEFT JOIN SUPPLIERS S
ON PC.SUPPLIERID=S.SUPPLIERID
LEFT JOIN CUSTOMERS C
ON PC.CUSTOMERID=C.CUSTOMERID
GO

-- 由 uvw_Purchases 檢視表, 取得所有採購單, 並依採購日期遞增排序
SELECT * FROM uvw_Purchases
ORDER BY PURCHASEDATE
GO

-- 由 uvw_Purchases 檢視表, 取得採購金額大於 50 萬以上的採購單, 並依採購日期遞增排序
SELECT * FROM uvw_Purchases
WHERE AMOUNT>500000
ORDER BY PURCHASEDATE
GO

-- 由 uvw_Purchases 檢視表, 取得 2010 年採購總金額大於 12 萬以上的廠商, 並依廠商代號遞增排序
-- Result Columns : SUPPLIERID, SUPPLIERNAME, AMOUT
SELECT SUPPLIERID,SUPPLIERNAME,SUM(AMOUNT) AMOUT FROM uvw_Purchases
WHERE PURCHASEDATE BETWEEN '20100101' AND '20101231'
GROUP BY SUPPLIERID,SUPPLIERNAME
HAVING SUM(AMOUNT)>120000
ORDER BY SUPPLIERID
GO
